### ISSUE TITLE
Firefox add-on to redirect bugzilla page to bzdeck

### ISSUE THREAD

**Issue by shinglyu** [kyoshino/bzdeck#250]
I'm thinking about something like [Wikiwand's addon](https://addons.mozilla.org/zh-tw/firefox/addon/wikiwand-wikipedia-modernized/). It redirects you to wikiwand page when you try to open a wikipedia link. If you really want to go to the original wikipedia page, you add `?oldformat=true` to the url. 

I can build that for you in, like, an afternoon. Will that be helpful?

**Comment by shinglyu** [comment]
I am also think about how I can click a bzdeck link in a Firefox stable release, and make it open in the nightly browser. It's kind of annoying to switch between stable and nightly.

**Comment by kyoshino** [comment]
:+1: to make an add-on. Or even a bookmarklet might be helpful.

About the compatibility: the limited browser support is intentional so far. BzDeck is a kind of a technical demo so I'd like to add the latest cool stuff to the app. Next week I'll implement the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) as Firefox 39 goes Aurora. BzDeck currently supports only bugzilla.mozilla.org and my guess is the most of Mozilla developers are using Nightly. In my case I'm using Stable and Nightly at the same time with [different profiles](http://kb.mozillazine.org/Opening_a_new_instance_of_Firefox_with_another_profile). I'd consider [expanding browser compatibility](https://github.com/kyoshino/bzdeck/issues/67) including non-Gecko browsers when BzDeck supports other Bugzilla installations than bugzilla.mozilla.org.

It would be nice if the add-on could automatically open BzDeck in Nightly if the installed browser is Stable.

**Comment by kyoshino** [comment]
Quick research: [`nsIProcess.run`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIProcess#run%28%29) can launch an app like this:
```js
const Cc = Components.classes;
const Ci = Components.interfaces;
let file = Cc['@mozilla.org/file/local;1'].createInstance(Ci.nsIFile);
let process = Cc['@mozilla.org/process/util;1'].createInstance(Ci.nsIProcess);
// TODO: Get a current URL path
let args = ['-no-remote', '-url https://www.bzdeck.com/']
// TODO: Detect platforms
file.initWithPath('/Applications/FirefoxNightly.app');
process.init(file);
process.run(false, args, args.length);
```

**Comment by shinglyu** [comment]
Wow, never know we can launch other app like that. I'll build a simple
addon that redirects single bug link to bzdeck first, then take some time
to see how to work with the `nsIProcess.run`

**Comment by shinglyu** [comment]
Here you are! https://github.com/shinglyu/bzdeck-addon

**Comment by shinglyu** [comment]
Binary: https://dl.dropboxusercontent.com/u/7281903/bzdeck_addon.xpi

**Comment by shinglyu** [comment]
If it's ok, I'll submit it to Firefox add-on gallery.

**Comment by kyoshino** [comment]
Awesome, thank you! Please submit it to Firefox Add-ons :+1:

**Comment by shinglyu** [comment]
Let me do this next Mon, its national holiday in Taiwan and I'm going on a
trip.

**Comment by shinglyu** [comment]
I failed to upload, seems like a server problem, I've submitted a bug to the add-on team: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1151389

**Comment by shinglyu** [comment]
Uploaded, waiting for review. https://addons.mozilla.org/en-US/firefox/addon/bzdeck/
@kyoshino : I choose a random icon. If you can provide an 64x64 icon in PNG or JPEG, I can update it.

**Comment by kyoshino** [comment]
@shinglyu Awesome! The 64x64 icon is [here](https://github.com/kyoshino/bzdeck/blob/master/webroot/static/images/logo/icon-64.png).

**Comment by shinglyu** [comment]
The add-on has passed full review, and the icon has been updated!

**Comment by kyoshino** [comment]
Wow, so quick! Thank you!

**Comment by kyoshino** [comment]
https://twitter.com/BzDeck/status/585480022368120832
https://www.facebook.com/BzDeck/posts/670099756449070
https://plus.google.com/+BzDeck/posts/8WdtQmnM1yc

**Comment by shinglyu** [comment]
(Y)
